server:
  port: 8761
  servlet:
    context-path: /eureka-service

spring:
  application:
    name: eureka-service

eureka:
  client:
    #registerWithEureka: false
    #fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka-service/eureka/
  server:
    peer-node-read-timeout-ms: 50000
    peer-node-connect-timeout-ms: 50000

logger:
  level:
    root: error