server:
  port: 8761
  servlet:
    context-path: /eureka-service

spring:
  application:
    name: eureka-service

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka-service/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0