server:
  port: 8090
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: create-order
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.106:3306/orders?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: cwh19891217
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 30
    initialSize: 5
    maxWait: 60000
    minIdle: 5
    timeBetweenEvictionRunsMillis: 60000
    minEvictionRunsMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.106:8080/eureka-service/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
seata:
  tx-service-group: order_service_tx_group
  client:
    support:
      spring:
        datasource-autoproxy: false
  service:
    grouplist:
      default: 192.168.1.106:8091
    vgroup-mapping:
      order_service_tx_group: default
  registry:
    type: eureka
    eureka:
      serviceUrl: http://192.168.1.106:8080/eureka-service/eureka/
      application: default

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: org.distribute.order.mapper